# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-20 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_mymodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='title',
        ),
    ]
