# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writer', '0004_mymodel_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='author',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mymodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
