# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writer', '0006_remove_mymodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
