# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0007_mymodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='content',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
