# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 06:11
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0011_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
