# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 17:27
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20180521_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_community',
            old_name='titie',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post_community',
            name='body',
        ),
        migrations.RemoveField(
            model_name='post_community',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='post_community',
            name='regdate',
        ),
        migrations.AddField(
            model_name='post_community',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_community',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=b' '),
        ),
    ]
