# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20180526_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_community',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
