# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-26 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comment_Community',
        ),
    ]
