# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=-1)),
            ],
        ),
    ]
