# Generated by Django 2.1.2 on 2018-10-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SolvedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pnum', models.IntegerField(default=0)),
            ],
        ),
    ]
