# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0002_remove_score_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('pnum', models.IntegerField(default=0)),
            ],
        ),
    ]
