# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-27 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0003_solvedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
